const POST_STATUS = {
    ACTIVE: 'ACTIVE',
    WAITING: 'WAITING',
    INACTIVE: 'INACTIVE',
    DELIVERY: 'DELIVERY',
    DELIVERED: 'DELIVERED',
    ACCOMPLISHED: 'ACCOMPLISHED',
    FAILURE: 'FAILURE',
};

export default POST_STATUS;
